- hosts: all
  become: true
  tasks:
    - name: Copy docker-compose.yml to the EC2 instance
      copy:
        src: ../../docker-compose.yml
        dest: /home/ec2-user/docker-compose.yml

    - name: Run docker-compose
      shell: docker-compose up -d
      args:
        chdir: /home/ec2-user/
